name: LiftForce
favicon: null
layout_spectrum: 0.24918
typography_spectrum: 0.40298
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f57b20'
    - '#3a3a3c'
    - '#ff0000'
    - '#000000'
    - '#aa5500'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
